# Generated by Django 4.2.24 on 2026-04-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='component',
            table='components',
        ),
        migrations.AlterModelTable(
            name='componenttype',
            table='component_types',
        ),
        migrations.AlterModelTable(
            name='status',
            table='statuses',
        ),
    ]
