# Generated by Django 4.2.24 on 2026-04-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_component_table_alter_componenttype_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='origin_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
