export const regions = [
  { name: 'Canada', value: 'CA' },
  { name: 'China', value: 'CN' },
  { name: 'Germany', value: 'DE' },
  { name: 'Iran', value: 'IR' },
  { name: 'Japan', value: 'JP' },
  { name: 'Russia', value: 'RU' },
  { name: 'Switzerland', value: 'CH' },
  { name: 'Taiwan', value: 'TW' },
  { name: 'Ukraine', value: 'UA' },
  { name: 'United Kingdom', value: 'GB' },
  { name: 'USA', value: 'US' }
];
export const typeDescriptions: Record<string, string> = {
  'Microcontroller': 'Controls and processes data in embedded systems',
  'GPS Module': 'Provides geolocation and positioning data',
  'Radio Module': 'Handles wireless communication',
  'Sensor': 'Detects environmental or physical changes',
  'Power Module': 'Manages power supply and distribution',
  'Memory': 'Stores data and instructions',
  'Antenna': 'Transmits and receives signals',
  'Camera Module': 'Captures visual data',
  'Flight Controller': 'Controls UAV flight dynamics',
  'Voltage Regulator': 'Stabilizes voltage levels',
  'Battery': 'Provides electrical power',
  'Connector': 'Connects components together',
  'PCB Board': 'Base board for electronic components',
  'Gyroscope': 'Measures rotation/orientation',
  'Accelerometer': 'Measures acceleration',
  'Servo': 'Controls precise movement',
  'Engine': 'Generates power',
};